# .github/workflows/firebase-hosting-merge.yml
# Déploiement automatique sur Firebase Hosting lors d'un merge sur main

name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Récupérer le code du repo
      - uses: actions/checkout@v4

      # 2️⃣ Installer les dépendances et build (ou remplacer par echo si pas de build)
      - name: Install & Build
        run: npm ci && npm run build
        # Pour un site statique HTML/CSS/JS, remplace la ligne ci-dessus par :
        # run: echo "No build needed"

      # 3️⃣ Déployer sur Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ASSO_CHAT62 }}
          projectId: asso-chat62
