# .github/workflows/firebase-hosting-merge.yml
# Déploiement automatique sur Firebase Hosting lors d'un push sur main

name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Récupérer le code du repo
      - uses: actions/checkout@v4

      # 2️⃣ Pas de build nécessaire pour HTML/CSS/JS
      - name: Skip build
        run: echo "No build needed"

      # 3️⃣ Déployer sur Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ASSO_CHAT62 }}
          projectId: asso-chat62
